services:
  - type: web
    name: automatic-control
    runtime: php
    plan: free
    buildCommand: |
      composer install
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://automatic-control.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromService:
          type: database
          name: automatic-db
          property: connectionString

databases:
  - name: automatic-db
    plan: free
